import type {Locale} from '@guide/contracts';
const en={
  send:'Capture current screen and send',
  consent:'When I press Capture and send, send a fresh image of my shared screen to Gemini. It may include visible personal information.',
  enabled:'Screen sending enabled',
  revoke:'Change / revoke',
  more:'More options',
  review:'Review before sending',
  instant:'Capture and send mode',
  retry:'Capture again',
  failed:"Couldn't capture this screen. Please try again.",
  privacyFailed:"We couldn't safely protect this screenshot. Please capture it again.",
  blocked:'Screen sending is disabled by strict privacy settings. Use reviewed labels or text.',
  share:'Share a screen first',
  preview:'Last sent snapshot',
  question:'What would you like help with?',
  voice:'Hear screen-sending consent',
  processing:'Capturing and sending…',
  reviewCapture:'Capture for review',
  reviewRetry:'Send this reviewed image again',
  risk:'Fresh captures include visible content. Old crops and masks are not reused.'
};
type Copy=typeof en;
const copy:Record<string,Copy>={
 'en-IN':en,
 'hi-IN':{
   send:'मौजूदा स्क्रीन कैप्चर करके भेजें',
   consent:'जब मैं कैप्चर करके भेजें दबाऊँ, मेरी साझा स्क्रीन की नई तस्वीर Gemini को भेजें। इसमें दिखाई देने वाली निजी जानकारी हो सकती है।',
   enabled:'स्क्रीन भेजना चालू है',
   revoke:'बदलें / अनुमति हटाएँ',
   more:'और विकल्प',
   review:'भेजने से पहले जाँचें',
   instant:'कैप्चर करके भेजने का मोड',
   retry:'फिर से कैप्चर करें',
   failed:'स्क्रीन कैप्चर नहीं हो सकी। कृपया फिर से कोशिश करें।',
   privacyFailed:'हम इस स्क्रीनशॉट की निजी जानकारी सुरक्षित नहीं कर सके। कृपया फिर से कोशिश करें।',
   blocked:'सख्त गोपनीयता सेटिंग में स्क्रीन भेजना बंद है। जाँचे हुए लेबल या टेक्स्ट इस्तेमाल करें।',
   share:'पहले स्क्रीन साझा करें',
   preview:'पिछली भेजी तस्वीर',
   question:'आप किस चीज़ में मदद चाहते हैं?',
   voice:'स्क्रीन भेजने की अनुमति सुनें',
   processing:'तस्वीर लेकर भेज रहे हैं…',
   reviewCapture:'जाँचने के लिए तस्वीर लें',
   reviewRetry:'यही जाँची तस्वीर फिर भेजें',
   risk:'नई तस्वीर में दिखाई देने वाली जानकारी शामिल है। पुराने क्रॉप और मास्क दोबारा नहीं लगते।'
 },
 'bn-IN':{
   send:'বর্তমান স্ক্রিনের ছবি তুলে পাঠান',
   consent:'আমি ছবি তুলে পাঠান চাপলে আমার শেয়ার করা স্ক্রিনের নতুন ছবি Gemini-তে পাঠান। এতে দৃশ্যমান ব্যক্তিগত তথ্য থাকতে পারে।',
   enabled:'স্ক্রিন পাঠানো চালু',
   revoke:'বদলান / অনুমতি বাতিল',
   more:'আরও বিকল্প',
   review:'পাঠানোর আগে দেখুন',
   instant:'ছবি তুলে পাঠানোর মোড',
   retry:'আবার ছবি তুলুন',
   failed:'স্ক্রিন ক্যাপচার করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।',
   privacyFailed:'এই স্ক্রিনশটের ব্যক্তিগত তথ্য সুরক্ষিত করা যায়নি। অনুগ্রহ করে আবার ছবি তুলুন।',
   blocked:'কঠোর গোপনীয়তায় স্ক্রিন পাঠানো বন্ধ। যাচাই করা লেবেল বা লেখা ব্যবহার করুন।',
   share:'আগে স্ক্রিন শেয়ার করুন',
   preview:'শেষ পাঠানো ছবি',
   question:'আপনি কী বিষয়ে সাহায্য চান?',
   voice:'স্ক্রিন পাঠানোর সম্মতি শুনুন',
   processing:'ছবি তুলে পাঠানো হচ্ছে…',
   reviewCapture:'দেখার জন্য ছবি তুলুন',
   reviewRetry:'এই দেখা ছবিটিই আবার পাঠান',
   risk:'নতুন ছবিতে দৃশ্যমান তথ্য থাকে। পুরোনো কাটছাঁট বা মাস্ক আবার লাগানো হয় না।'
 },
 'mr-IN':{
   send:'सध्याची स्क्रीन कॅप्चर करून पाठवा',
   consent:'मी कॅप्चर करून पाठवा दाबल्यावर माझ्या सामायिक स्क्रीनचे नवीन चित्र Gemini कडे पाठवा. त्यात दिसणारी वैयक्तिक माहिती असू शकते.',
   enabled:'स्क्रीन पाठवणे सुरू',
   revoke:'बदला / परवानगी रद्द',
   more:'आणखी पर्याय',
   review:'पाठवण्यापूर्वी तपासा',
   instant:'कॅप्चर करून पाठवण्याचा मोड',
   retry:'पुन्हा कॅप्चर करा',
   failed:'स्क्रीन कॅप्चर करता आली नाही. कृपया पुन्हा प्रयत्न करा.',
   privacyFailed:'या स्क्रीनशॉटमधील खाजगी माहिती सुरक्षित करता आली नाही. कृपया पुन्हा प्रयत्न करा.',
   blocked:'कडक गोपनीयता सेटिंगमध्ये स्क्रीन पाठवणे बंद आहे. तपासलेली लेबले किंवा मजकूर वापरा.',
   share:'आधी स्क्रीन सामायिक करा',
   preview:'मागील पाठवलेले चित्र',
   question:'तुम्हाला कशात मदत हवी आहे?',
   voice:'स्क्रीन पाठवण्याची संमती ऐका',
   processing:'चित्र घेऊन पाठवत आहोत…',
   reviewCapture:'तपासण्यासाठी चित्र घ्या',
   reviewRetry:'हेच तपासलेले चित्र पुन्हा पाठवा',
   risk:'नवीन चित्रात दिसणारी माहिती असते. जुने क्रॉप आणि मास्क पुन्हा वापरले जात नाहीत.'
 },
 'te-IN':{
   send:'ప్రస్తుత స్క్రీన్ చిత్రం తీసి పంపండి',
   consent:'నేను చిత్రం తీసి పంపండి నొక్కినప్పుడు నా షేర్ చేసిన స్క్రీన్ కొత్త చిత్రాన్ని Geminiకి పంపండి. అందులో కనిపించే వ్యక్తిగత సమాచారం ఉండవచ్చు.',
   enabled:'స్క్రీన్ పంపడం ప్రారంభమైంది',
   revoke:'మార్చండి / అనుమతి రద్దు',
   more:'మరిన్ని ఎంపికలు',
   review:'పంపే ముందు పరిశీలించండి',
   instant:'చిత్రం తీసి పంపే విధానం',
   retry:'మళ్లీ చిత్రం తీయండి',
   failed:'స్క్రీన్ చిత్రం తీయడం సాధ్యపడలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
   privacyFailed:'ఈ స్క్రీన్‌షాట్‌లోని వ్యక్తిగత సమాచారాన్ని భద్రపరచడం సాధ్యపడలేదు. దయచేసి మళ్లీ చిత్రం తీయండి.',
   blocked:'కఠిన గోప్యత సెట్టింగుల్లో స్క్రీన్ పంపడం నిలిపివేయబడింది. పరిశీలించిన లేబుళ్లు లేదా వచనం వాడండి.',
   share:'ముందు స్క్రీన్ షేర్ చేయండి',
   preview:'చివరిగా పంపిన చిత్రం',
   question:'మీకు ఏ విషయంలో సహాయం కావాలి?',
   voice:'స్క్రీన్ పంపే సమ్మతి వినండి',
   processing:'చిత్రం తీసి పంపుతున్నాం…',
   reviewCapture:'పరిశీలించడానికి చిత్రం తీయండి',
   reviewRetry:'ఈ పరిశీలించిన చిత్రాన్ని మళ్లీ పంపండి',
   risk:'కొత్త చిత్రంలో కనిపించే సమాచారం ఉంటుంది. పాత క్రాప్ లేదా మాస్క్‌లు మళ్లీ వర్తించవు.'
 }
};
export const captureWords=(locale:Locale):Copy=>copy[locale]||en;

