import type {Locale} from '@guide/contracts';
const en={hero:'A little guidance. A lot more confidence.',language:'Language',accessibility:'Accessibility',history:'History',account:'Account',help:'Help',settings:'Settings',again:'Start again',conversation:'Conversation',screen:'Screen',welcome:'Your next step, made clearer.',choose:'Speak, share or type. We’ll take it one step at a time.',voice:'Spoken guidance',visual:'Help with your screen',typing:'Type when you prefer',feedback:'Feedback',edit:'Edit screenshot',details:'Read the full explanation',caption:'Assistant message'};
const translated:Partial<Record<Locale,typeof en>>={
'hi-IN':{hero:'थोड़ी मदद। बहुत सारा आत्मविश्वास।',language:'भाषा',accessibility:'सुगम्यता',history:'इतिहास',account:'खाता',help:'मदद',settings:'सेटिंग',again:'फिर शुरू करें',conversation:'बातचीत',screen:'स्क्रीन',welcome:'आपका अगला कदम, अब आसान।',choose:'बोलें, साझा करें या लिखें। एक बार में एक कदम।',voice:'बोलकर मार्गदर्शन',visual:'आपकी स्क्रीन पर मदद',typing:'चाहें तो लिखें',feedback:'प्रतिक्रिया',edit:'स्क्रीनशॉट संपादित करें',details:'पूरा विवरण पढ़ें',caption:'सहायक का संदेश'},
'bn-IN':{hero:'একটু সহায়তা। অনেকটা আত্মবিশ্বাস।',language:'ভাষা',accessibility:'সহজ ব্যবহার',history:'ইতিহাস',account:'অ্যাকাউন্ট',help:'সাহায্য',settings:'সেটিংস',again:'আবার শুরু করুন',conversation:'কথোপকথন',screen:'স্ক্রিন',welcome:'আপনার পরের ধাপ আরও সহজ।',choose:'বলুন, শেয়ার করুন বা লিখুন। একবারে একটি ধাপ।',voice:'কথায় নির্দেশনা',visual:'আপনার স্ক্রিনে সাহায্য',typing:'চাইলে লিখুন',feedback:'মতামত',edit:'স্ক্রিনশট সম্পাদনা',details:'পুরো ব্যাখ্যা পড়ুন',caption:'সহায়কের বার্তা'},
'mr-IN':{hero:'थोडी मदत. भरपूर आत्मविश्वास.',language:'भाषा',accessibility:'सुलभता',history:'इतिहास',account:'खाते',help:'मदत',settings:'सेटिंग्ज',again:'पुन्हा सुरू करा',conversation:'संवाद',screen:'स्क्रीन',welcome:'तुमचे पुढचे पाऊल आता सोपे.',choose:'बोला, शेअर करा किंवा लिहा. एकावेळी एक पाऊल.',voice:'बोलून मार्गदर्शन',visual:'तुमच्या स्क्रीनवर मदत',typing:'हवे तर लिहा',feedback:'अभिप्राय',edit:'स्क्रीनशॉट संपादित करा',details:'पूर्ण स्पष्टीकरण वाचा',caption:'सहाय्यकाचा संदेश'},
'te-IN':{hero:'కొంచెం సహాయం. మరింత ఆత్మవిశ్వాసం.',language:'భాష',accessibility:'సులభ వినియోగం',history:'చరిత్ర',account:'ఖాతా',help:'సహాయం',settings:'సెట్టింగ్‌లు',again:'మళ్లీ ప్రారంభించండి',conversation:'సంభాషణ',screen:'స్క్రీన్',welcome:'మీ తదుపరి అడుగు మరింత సులభం.',choose:'మాట్లాడండి, షేర్ చేయండి లేదా రాయండి. ఒక్కో అడుగు వేద్దాం.',voice:'మాటలతో మార్గదర్శనం',visual:'మీ స్క్రీన్‌తో సహాయం',typing:'కావాలంటే టైప్ చేయండి',feedback:'అభిప్రాయం',edit:'స్క్రీన్‌షాట్ సవరించండి',details:'పూర్తి వివరణ చదవండి',caption:'సహాయకుని సందేశం'}
};
const product:Partial<Record<Locale,string>>={'en-IN':'Access digital information simply by talking. Multilingual guidance for reading, typing and navigating unfamiliar websites.','hi-IN':'सिर्फ बात करके डिजिटल जानकारी पाएँ। पढ़ने, लिखने और अनजान वेबसाइटों को समझने में अपनी भाषा में मदद लें।','bn-IN':'শুধু কথা বলেই ডিজিটাল তথ্য পান। পড়া, লেখা ও অপরিচিত ওয়েবসাইট ব্যবহারে নিজের ভাষায় সাহায্য নিন।','mr-IN':'फक्त बोलून डिजिटल माहिती मिळवा. वाचणे, लिहिणे आणि अनोळखी वेबसाइट वापरण्यासाठी आपल्या भाषेत मदत घ्या.','te-IN':'మాట్లాడటం ద్వారానే డిజిటల్ సమాచారం పొందండి. చదవడానికి, టైప్ చేయడానికి, కొత్త వెబ్‌సైట్‌లను ఉపయోగించడానికి మీ భాషలో సహాయం పొందండి.'};
export const designWords=(locale:Locale)=>({...translated[locale]||en,product:product[locale]||product['en-IN']!,close:({'en-IN':'Close','hi-IN':'बंद करें','bn-IN':'বন্ধ করুন','mr-IN':'बंद करा','te-IN':'మూసివేయండి'} as Partial<Record<Locale,string>>)[locale]||'Close'});
