import type { Locale } from '@guide/contracts';
const en = {
  title: 'A little guidance. A lot more confidence.', intro: 'Get help with websites, forms and email. In your language, one step at a time.',
  choose: 'Choose your assistance language', interface: 'Language for these controls', continue: 'Continue', back: 'Change language',
  signIn: 'Sign in', signUp: 'Create account', email: 'Email address', password: 'Password', reset: 'Reset password', signOut: 'Sign out',
  question: 'What would you like help with?', input: 'Question language', reply: 'Assistance language', draft: 'Draft language', chooseDraft: 'Choose a draft language',
  send: 'Send question', stop: 'Stop answer', working: 'Preparing your guidance…', idle: 'Ready when you are.',
  welcome: 'Your next step starts here.', task: 'What are we working on?', general: 'Understand a task', guide: 'Find my next step', emailTask: 'Prepare a draft',
  open: 'Open chat', close: 'Close chat', pin: 'Pin visible', safe: 'I have used only public instructions or synthetic examples, with no personal details.',
  preview: 'Add a screenshot', review: 'Review safe labels', approve: 'Approve selected context', end: 'End and clear session',
  privacy: 'Screenshots stay on this device. Only the labels you select and approve are sent with your question.',
  unavailable: 'This service is not ready. You can keep your question and try again after setup.',
  verify: 'Verify your email to ask a question.', resend: 'Send verification email', checked: 'I have verified my email',
  accountHelp: 'Check your details or use password reset. Please try again.', sent: 'Check your inbox for the account email.',
  error: 'We could not finish. Your question is still here. Check your connection or try again.',
  consentError: 'Review your question and confirm it contains no personal details.', stopped: 'Stopped. Your question is still here.',
  sourceChanged: 'The context changed. Review it again before asking.', copy: 'Copy draft', copied: 'Draft copied. Review it before sending.',
  noHistory: 'History is off. Answers are not saved.', useReader: 'Use my screen reader', larger: 'Larger text',
};
type Catalog = typeof en;
// Initial translations: functional catalog coverage, awaiting native-speaker review.
const hi: Catalog = { title: 'थोड़ी मदद। अधिक आत्मविश्वास।', intro: 'वेबसाइट, फ़ॉर्म और ईमेल में अपनी भाषा में, एक-एक कदम पर मदद पाएँ।', choose: 'सहायता की भाषा चुनें', interface: 'इन बटनों की भाषा', continue: 'आगे बढ़ें', back: 'भाषा बदलें', signIn: 'साइन इन करें', signUp: 'खाता बनाएँ', email: 'ईमेल पता', password: 'पासवर्ड', reset: 'पासवर्ड रीसेट करें', signOut: 'साइन आउट करें', question: 'आपको किस काम में मदद चाहिए?', input: 'प्रश्न की भाषा', reply: 'सहायता की भाषा', draft: 'मसौदे की भाषा', chooseDraft: 'मसौदे की भाषा चुनें', send: 'प्रश्न भेजें', stop: 'उत्तर रोकें', working: 'आपके लिए मार्गदर्शन तैयार हो रहा है…', idle: 'जब आप तैयार हों।', welcome: 'आपका अगला कदम यहाँ से शुरू होता है।', task: 'हम किस काम पर मदद करें?', general: 'काम समझें', guide: 'अगला कदम जानें', emailTask: 'मसौदा तैयार करें', open: 'चैट खोलें', close: 'चैट बंद करें', pin: 'खुला रखें', safe: 'मैंने केवल सार्वजनिक निर्देश या काल्पनिक उदाहरण दिए हैं, कोई निजी जानकारी नहीं।', preview: 'स्क्रीनशॉट जोड़ें', review: 'सुरक्षित लेबल जाँचें', approve: 'चुनी हुई जानकारी की अनुमति दें', end: 'सत्र समाप्त करके साफ़ करें', privacy: 'स्क्रीनशॉट इसी डिवाइस पर रहते हैं। केवल आपके चुने और स्वीकृत लेबल प्रश्न के साथ भेजे जाते हैं।', unavailable: 'यह सेवा अभी तैयार नहीं है। अपना प्रश्न रखें और सेटअप के बाद फिर कोशिश करें।', verify: 'प्रश्न पूछने के लिए अपना ईमेल सत्यापित करें।', resend: 'सत्यापन ईमेल भेजें', checked: 'मैंने ईमेल सत्यापित कर लिया है', accountHelp: 'अपनी जानकारी जाँचें या पासवर्ड रीसेट करें। फिर कोशिश करें।', sent: 'खाते के ईमेल के लिए अपना इनबॉक्स देखें।', error: 'काम पूरा नहीं हुआ। आपका प्रश्न यहीं है। कनेक्शन जाँचें या फिर कोशिश करें।', consentError: 'प्रश्न जाँचें और पुष्टि करें कि इसमें निजी जानकारी नहीं है।', stopped: 'रोक दिया गया। आपका प्रश्न यहीं है।', sourceChanged: 'जानकारी बदल गई है। पूछने से पहले फिर जाँचें।', copy: 'मसौदा कॉपी करें', copied: 'मसौदा कॉपी हुआ। भेजने से पहले जाँचें।', noHistory: 'इतिहास बंद है। उत्तर सहेजे नहीं जाते।', useReader: 'मेरा स्क्रीन रीडर उपयोग करें', larger: 'बड़ा पाठ' };
const bn: Catalog = { title: 'একটু সহায়তা। অনেক বেশি আত্মবিশ্বাস।', intro: 'ওয়েবসাইট, ফর্ম ও ইমেলে নিজের ভাষায় ধাপে ধাপে সহায়তা পান।', choose: 'সহায়তার ভাষা বাছুন', interface: 'এই নিয়ন্ত্রণগুলির ভাষা', continue: 'এগিয়ে যান', back: 'ভাষা বদলান', signIn: 'সাইন ইন', signUp: 'অ্যাকাউন্ট তৈরি করুন', email: 'ইমেল ঠিকানা', password: 'পাসওয়ার্ড', reset: 'পাসওয়ার্ড রিসেট', signOut: 'সাইন আউট', question: 'কোন কাজে সাহায্য চান?', input: 'প্রশ্নের ভাষা', reply: 'সহায়তার ভাষা', draft: 'খসড়ার ভাষা', chooseDraft: 'খসড়ার ভাষা বাছুন', send: 'প্রশ্ন পাঠান', stop: 'উত্তর থামান', working: 'নির্দেশনা তৈরি হচ্ছে…', idle: 'আপনি প্রস্তুত হলে শুরু করুন।', welcome: 'আপনার পরের ধাপ এখান থেকে।', task: 'কোন কাজটি করবেন?', general: 'কাজটি বুঝুন', guide: 'পরের ধাপ খুঁজুন', emailTask: 'খসড়া তৈরি করুন', open: 'চ্যাট খুলুন', close: 'চ্যাট বন্ধ করুন', pin: 'খোলা রাখুন', safe: 'শুধু প্রকাশ্য নির্দেশ বা কাল্পনিক উদাহরণ দিয়েছি, ব্যক্তিগত তথ্য নয়।', preview: 'স্ক্রিনশট যোগ করুন', review: 'নিরাপদ লেবেল দেখুন', approve: 'বাছাই করা তথ্য অনুমোদন করুন', end: 'সেশন শেষ করে মুছুন', privacy: 'স্ক্রিনশট এই ডিভাইসেই থাকে। কেবল বাছাই ও অনুমোদিত লেবেল প্রশ্নের সঙ্গে যায়।', unavailable: 'পরিষেবা প্রস্তুত নয়। প্রশ্নটি রেখে সেটআপের পরে চেষ্টা করুন।', verify: 'প্রশ্ন করতে ইমেল যাচাই করুন।', resend: 'যাচাই ইমেল পাঠান', checked: 'ইমেল যাচাই করেছি', accountHelp: 'তথ্য পরীক্ষা করুন বা পাসওয়ার্ড রিসেট করে আবার চেষ্টা করুন।', sent: 'অ্যাকাউন্টের ইমেলের জন্য ইনবক্স দেখুন।', error: 'শেষ করা যায়নি। প্রশ্নটি আছে। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।', consentError: 'প্রশ্নে ব্যক্তিগত তথ্য নেই নিশ্চিত করুন।', stopped: 'থামানো হয়েছে। প্রশ্নটি আছে।', sourceChanged: 'তথ্য বদলেছে। আবার পর্যালোচনা করুন।', copy: 'খসড়া কপি করুন', copied: 'কপি হয়েছে। পাঠানোর আগে দেখুন।', noHistory: 'ইতিহাস বন্ধ। উত্তর সেভ হয় না।', useReader: 'আমার স্ক্রিন রিডার ব্যবহার করুন', larger: 'বড় লেখা' };
const mr: Catalog = { title: 'थोडी मदत. अधिक आत्मविश्वास.', intro: 'वेबसाइट, फॉर्म आणि ईमेलसाठी तुमच्या भाषेत टप्प्याटप्प्याने मदत मिळवा.', choose: 'मदतीची भाषा निवडा', interface: 'या नियंत्रणांची भाषा', continue: 'पुढे जा', back: 'भाषा बदला', signIn: 'साइन इन करा', signUp: 'खाते तयार करा', email: 'ईमेल पत्ता', password: 'पासवर्ड', reset: 'पासवर्ड रीसेट करा', signOut: 'साइन आउट करा', question: 'कोणत्या कामात मदत हवी?', input: 'प्रश्नाची भाषा', reply: 'मदतीची भाषा', draft: 'मसुद्याची भाषा', chooseDraft: 'मसुद्याची भाषा निवडा', send: 'प्रश्न पाठवा', stop: 'उत्तर थांबवा', working: 'मार्गदर्शन तयार होत आहे…', idle: 'तुम्ही तयार असाल तेव्हा.', welcome: 'तुमचे पुढचे पाऊल येथून.', task: 'कोणत्या कामासाठी मदत हवी?', general: 'काम समजून घ्या', guide: 'पुढचे पाऊल शोधा', emailTask: 'मसुदा तयार करा', open: 'चॅट उघडा', close: 'चॅट बंद करा', pin: 'उघडे ठेवा', safe: 'मी फक्त सार्वजनिक सूचना किंवा काल्पनिक उदाहरणे दिली आहेत, वैयक्तिक माहिती नाही.', preview: 'स्क्रीनशॉट जोडा', review: 'सुरक्षित लेबले तपासा', approve: 'निवडलेल्या माहितीला परवानगी द्या', end: 'सत्र संपवून साफ करा', privacy: 'स्क्रीनशॉट याच उपकरणावर राहतात. फक्त निवडलेली व मंजूर लेबले प्रश्नासोबत जातात.', unavailable: 'सेवा तयार नाही. प्रश्न जपून ठेवा आणि सेटअपनंतर प्रयत्न करा.', verify: 'प्रश्न विचारण्यासाठी ईमेल सत्यापित करा.', resend: 'सत्यापन ईमेल पाठवा', checked: 'मी ईमेल सत्यापित केला आहे', accountHelp: 'माहिती तपासा किंवा पासवर्ड रीसेट करून पुन्हा प्रयत्न करा.', sent: 'खात्याच्या ईमेलसाठी इनबॉक्स तपासा.', error: 'पूर्ण झाले नाही. प्रश्न येथेच आहे. जोडणी तपासा किंवा पुन्हा प्रयत्न करा.', consentError: 'प्रश्नात वैयक्तिक माहिती नाही याची खात्री करा.', stopped: 'थांबवले. प्रश्न येथेच आहे.', sourceChanged: 'माहिती बदलली. पुन्हा तपासा.', copy: 'मसुदा कॉपी करा', copied: 'मसुदा कॉपी झाला. पाठवण्यापूर्वी तपासा.', noHistory: 'इतिहास बंद आहे. उत्तरे जतन होत नाहीत.', useReader: 'माझा स्क्रीन रीडर वापरा', larger: 'मोठा मजकूर' };
const te: Catalog = { title: 'కొంచెం సహాయం. మరింత ఆత్మవిశ్వాసం.', intro: 'వెబ్‌సైట్లు, ఫారాలు, ఇమెయిల్ కోసం మీ భాషలో ఒక్కో అడుగుగా సహాయం పొందండి.', choose: 'సహాయ భాషను ఎంచుకోండి', interface: 'ఈ నియంత్రణల భాష', continue: 'కొనసాగించండి', back: 'భాష మార్చండి', signIn: 'సైన్ ఇన్', signUp: 'ఖాతా సృష్టించండి', email: 'ఇమెయిల్ చిరునామా', password: 'పాస్‌వర్డ్', reset: 'పాస్‌వర్డ్ రీసెట్', signOut: 'సైన్ అవుట్', question: 'ఏ పనిలో సహాయం కావాలి?', input: 'ప్రశ్న భాష', reply: 'సహాయ భాష', draft: 'ముసాయిదా భాష', chooseDraft: 'ముసాయిదా భాషను ఎంచుకోండి', send: 'ప్రశ్న పంపండి', stop: 'సమాధానం ఆపండి', working: 'మార్గదర్శనం సిద్ధమవుతోంది…', idle: 'మీరు సిద్ధంగా ఉన్నప్పుడు.', welcome: 'మీ తదుపరి అడుగు ఇక్కడ మొదలవుతుంది.', task: 'ఏ పని చేస్తున్నాం?', general: 'పనిని అర్థం చేసుకోండి', guide: 'తదుపరి అడుగు తెలుసుకోండి', emailTask: 'ముసాయిదా తయారు చేయండి', open: 'చాట్ తెరవండి', close: 'చాట్ మూసివేయండి', pin: 'తెరిచి ఉంచండి', safe: 'పబ్లిక్ సూచనలు లేదా కల్పిత ఉదాహరణలు మాత్రమే ఇచ్చాను, వ్యక్తిగత వివరాలు లేవు.', preview: 'స్క్రీన్‌షాట్ జోడించండి', review: 'సురక్షిత లేబుళ్లను సమీక్షించండి', approve: 'ఎంచుకున్న సమాచారాన్ని ఆమోదించండి', end: 'సెషన్ ముగించి తొలగించండి', privacy: 'స్క్రీన్‌షాట్లు ఈ పరికరంలోనే ఉంటాయి. ఎంచుకుని ఆమోదించిన లేబుళ్లు మాత్రమే ప్రశ్నతో పంపబడతాయి.', unavailable: 'సేవ సిద్ధంగా లేదు. ప్రశ్నను ఉంచి సెటప్ తర్వాత మళ్లీ ప్రయత్నించండి.', verify: 'ప్రశ్న అడగడానికి ఇమెయిల్ ధృవీకరించండి.', resend: 'ధృవీకరణ ఇమెయిల్ పంపండి', checked: 'ఇమెయిల్ ధృవీకరించాను', accountHelp: 'వివరాలు తనిఖీ చేయండి లేదా పాస్‌వర్డ్ రీసెట్ చేసి మళ్లీ ప్రయత్నించండి.', sent: 'ఖాతా ఇమెయిల్ కోసం ఇన్‌బాక్స్ చూడండి.', error: 'పూర్తి కాలేదు. ప్రశ్న ఇక్కడే ఉంది. కనెక్షన్ తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.', consentError: 'ప్రశ్నలో వ్యక్తిగత వివరాలు లేవని నిర్ధారించండి.', stopped: 'ఆపబడింది. ప్రశ్న ఇక్కడే ఉంది.', sourceChanged: 'సమాచారం మారింది. మళ్లీ సమీక్షించండి.', copy: 'ముసాయిదా కాపీ చేయండి', copied: 'కాపీ అయింది. పంపే ముందు తనిఖీ చేయండి.', noHistory: 'చరిత్ర ఆఫ్‌లో ఉంది. సమాధానాలు సేవ్ కావు.', useReader: 'నా స్క్రీన్ రీడర్ వాడండి', larger: 'పెద్ద అక్షరాలు' };
const ta: Catalog = { title: 'சிறிது உதவி. அதிக நம்பிக்கை.', intro: 'இணையதளங்கள், படிவங்கள், மின்னஞ்சல்களுக்கு உங்கள் மொழியில் படிப்படியாக உதவி பெறுங்கள்.', choose: 'உதவி மொழியைத் தேர்ந்தெடுக்கவும்', interface: 'இந்தக் கட்டுப்பாடுகளின் மொழி', continue: 'தொடரவும்', back: 'மொழியை மாற்றவும்', signIn: 'உள்நுழையவும்', signUp: 'கணக்கை உருவாக்கவும்', email: 'மின்னஞ்சல் முகவரி', password: 'கடவுச்சொல்', reset: 'கடவுச்சொல்லை மீட்டமைக்கவும்', signOut: 'வெளியேறவும்', question: 'எந்தப் பணியில் உதவி வேண்டும்?', input: 'கேள்வி மொழி', reply: 'உதவி மொழி', draft: 'வரைவு மொழி', chooseDraft: 'வரைவு மொழியைத் தேர்ந்தெடுக்கவும்', send: 'கேள்வியை அனுப்பவும்', stop: 'பதிலை நிறுத்தவும்', working: 'வழிகாட்டல் தயாராகிறது…', idle: 'நீங்கள் தயாராக இருக்கும்போது.', welcome: 'அடுத்த படி இங்கே தொடங்குகிறது.', task: 'என்ன வேலை செய்கிறோம்?', general: 'பணியைப் புரிந்துகொள்ளவும்', guide: 'அடுத்த படியைக் கண்டறியவும்', emailTask: 'வரைவு தயாரிக்கவும்', open: 'அரட்டையைத் திறக்கவும்', close: 'அரட்டையை மூடவும்', pin: 'திறந்தே வைக்கவும்', safe: 'பொது வழிமுறைகள் அல்லது கற்பனை உதாரணங்கள் மட்டுமே உள்ளன; தனிப்பட்ட தகவல்கள் இல்லை.', preview: 'திரைப்பிடிப்பைச் சேர்க்கவும்', review: 'பாதுகாப்பான பெயர்களைச் சரிபார்க்கவும்', approve: 'தேர்ந்தெடுத்த தகவலை ஒப்புக்கொள்ளவும்', end: 'அமர்வை முடித்து அழிக்கவும்', privacy: 'திரைப்பிடிப்புகள் இந்தச் சாதனத்திலேயே இருக்கும். நீங்கள் தேர்ந்தெடுத்து ஒப்புக்கொண்ட பெயர்கள் மட்டுமே கேள்வியுடன் அனுப்பப்படும்.', unavailable: 'சேவை தயாராக இல்லை. கேள்வியை வைத்திருந்து அமைத்த பிறகு முயலவும்.', verify: 'கேள்வி கேட்க மின்னஞ்சலை உறுதிப்படுத்தவும்.', resend: 'உறுதிப்படுத்தும் மின்னஞ்சலை அனுப்பவும்', checked: 'மின்னஞ்சலை உறுதிப்படுத்திவிட்டேன்', accountHelp: 'விவரங்களைச் சரிபார்க்கவும் அல்லது கடவுச்சொல்லை மீட்டமைத்து முயலவும்.', sent: 'கணக்கு மின்னஞ்சலுக்கு உங்கள் அஞ்சல் பெட்டியைப் பார்க்கவும்.', error: 'முடிக்க முடியவில்லை. கேள்வி இங்கே உள்ளது. இணைப்பைச் சரிபார்த்து மீண்டும் முயலவும்.', consentError: 'கேள்வியில் தனிப்பட்ட தகவல் இல்லை என உறுதிப்படுத்தவும்.', stopped: 'நிறுத்தப்பட்டது. கேள்வி இங்கே உள்ளது.', sourceChanged: 'தகவல் மாறிவிட்டது. மீண்டும் சரிபார்க்கவும்.', copy: 'வரைவை நகலெடுக்கவும்', copied: 'நகலெடுக்கப்பட்டது. அனுப்புமுன் சரிபார்க்கவும்.', noHistory: 'வரலாறு முடக்கப்பட்டுள்ளது. பதில்கள் சேமிக்கப்படாது.', useReader: 'எனது திரை வாசிப்பானைப் பயன்படுத்தவும்', larger: 'பெரிய எழுத்து' };
const ur: Catalog = { title: 'تھوڑی مدد۔ زیادہ اعتماد۔', intro: 'ویب سائٹس، فارم اور ای میل میں اپنی زبان میں قدم بہ قدم مدد حاصل کریں۔', choose: 'مدد کی زبان منتخب کریں', interface: 'ان کنٹرولز کی زبان', continue: 'آگے بڑھیں', back: 'زبان بدلیں', signIn: 'سائن ان کریں', signUp: 'اکاؤنٹ بنائیں', email: 'ای میل پتہ', password: 'پاس ورڈ', reset: 'پاس ورڈ دوبارہ بنائیں', signOut: 'سائن آؤٹ کریں', question: 'کس کام میں مدد چاہیے؟', input: 'سوال کی زبان', reply: 'مدد کی زبان', draft: 'مسودے کی زبان', chooseDraft: 'مسودے کی زبان منتخب کریں', send: 'سوال بھیجیں', stop: 'جواب روکیں', working: 'رہنمائی تیار ہو رہی ہے…', idle: 'جب آپ تیار ہوں۔', welcome: 'آپ کا اگلا قدم یہاں سے۔', task: 'ہم کس کام میں مدد کریں؟', general: 'کام سمجھیں', guide: 'اگلا قدم معلوم کریں', emailTask: 'مسودہ تیار کریں', open: 'چیٹ کھولیں', close: 'چیٹ بند کریں', pin: 'کھلا رکھیں', safe: 'صرف عوامی ہدایات یا فرضی مثالیں دی ہیں، ذاتی تفصیلات نہیں۔', preview: 'اسکرین شاٹ شامل کریں', review: 'محفوظ لیبل دیکھیں', approve: 'منتخب معلومات کی منظوری دیں', end: 'سیشن ختم کرکے صاف کریں', privacy: 'اسکرین شاٹ اسی آلے پر رہتے ہیں۔ صرف منتخب اور منظور شدہ لیبل سوال کے ساتھ بھیجے جاتے ہیں۔', unavailable: 'سروس تیار نہیں۔ سوال محفوظ رکھیں اور سیٹ اپ کے بعد کوشش کریں۔', verify: 'سوال پوچھنے کے لیے ای میل کی تصدیق کریں۔', resend: 'تصدیقی ای میل بھیجیں', checked: 'میں نے ای میل کی تصدیق کر لی ہے', accountHelp: 'تفصیلات دیکھیں یا پاس ورڈ دوبارہ بنا کر کوشش کریں۔', sent: 'اکاؤنٹ کی ای میل کے لیے ان باکس دیکھیں۔', error: 'مکمل نہیں ہوا۔ سوال یہیں ہے۔ کنکشن دیکھ کر دوبارہ کوشش کریں۔', consentError: 'تصدیق کریں کہ سوال میں ذاتی تفصیلات نہیں ہیں۔', stopped: 'روک دیا گیا۔ سوال یہیں ہے۔', sourceChanged: 'معلومات بدل گئی ہیں۔ دوبارہ جائزہ لیں۔', copy: 'مسودہ کاپی کریں', copied: 'کاپی ہو گیا۔ بھیجنے سے پہلے دیکھیں۔', noHistory: 'تاریخ بند ہے۔ جوابات محفوظ نہیں ہوتے۔', useReader: 'میرا اسکرین ریڈر استعمال کریں', larger: 'بڑا متن' };
export const catalogs: Record<Locale, Catalog> = { 'en-IN': en, 'hi-IN': hi, 'bn-IN': bn, 'mr-IN': mr, 'te-IN': te, 'ta-IN': ta, 'ur-IN': ur };
export type { Catalog };
