'use client';
import { useState } from 'react';
import { EmailAuthProvider, reauthenticateWithCredential, signOut } from 'firebase/auth';
import type { Answer, Locale } from '@guide/contracts';
import { api } from '../lib/api';
import { firebaseAuth } from '../lib/firebase';
import { useWords } from '../lib/messages';

export function AccountTools({ sessionId, locale, onDeleted, mode }: { mode:'history'|'account'|'feedback'; sessionId: string | null; locale: Locale; onDeleted: () => void }) {
  const { m, uiLocale } = useWords();
  const [items, setItems] = useState<{ _id: string; updatedAt: string }[]>([]), [turns, setTurns] = useState<{ question: string; answer: Answer }[]>([]);
  const [selected, setSelected] = useState(''), [text, setText] = useState(''), [rating, setRating] = useState(''), [consent, setConsent] = useState(false);
  const [deleting, setDeleting] = useState(false), [password, setPassword] = useState(''), [busy, setBusy] = useState(false), [status, setStatus] = useState('');
  async function work(action: () => Promise<void>) { setBusy(true); setStatus(''); try { await action(); } catch { setStatus(m("This action did not finish. Check your connection and try again. Account deletion may need a recent sign-in.")); } finally { setBusy(false); } }
  async function refresh() { const result = await api<{ items: typeof items }>('/sessions'); setItems(result.items); }
  return <section className="card" lang={uiLocale}>{mode==='history'&&<><h3>{m("Saved sessions")}</h3><p className="hint">{m("Only sessions started with saving enabled appear here. Saved text expires after 30 days. Raw screenshots and recordings are never saved.")}</p><button type="button" className="secondary" disabled={busy} onClick={() => void work(refresh)}>{m("Refresh saved sessions")}</button><ul>{items.map(item => <li key={item._id}><button type="button" className="text-button" disabled={busy} onClick={() => void work(async () => { const result = await api<{ turns: typeof turns }>(`/sessions/${item._id}/history`); setTurns(result.turns); setSelected(item._id); })}>{new Date(item.updatedAt).toLocaleString(locale)}</button><button type="button" className="text-button" disabled={busy} onClick={() => void work(async () => { await api(`/sessions/${item._id}`, 'DELETE'); if (selected === item._id) { setTurns([]); setSelected(''); } await refresh(); })}>{m("Delete saved session")}</button></li>)}</ul>{turns.map(item => <article key={item.answer.requestId}><p>{item.question}</p><p lang={item.answer.explanation.locale}>{item.answer.explanation.text}</p>{item.answer.draft && <pre lang={item.answer.draft.locale}>{item.answer.draft.text}</pre>}</article>)}
    </>}{mode==='feedback'&&<><h3>{m("Feedback")}</h3><label>{m("Was the guidance useful?")}<select value={rating} onChange={e => setRating(e.target.value)}><option value="" disabled>{m("Choose a rating")}</option><option value="helpful">{m("Helpful")}</option><option value="not-helpful">{m("Not helpful")}</option></select></label><label>{m("Optional comment, without personal details")}<textarea maxLength={500} value={text} onChange={e => { setText(e.target.value); setConsent(false); }}/></label><label className="check"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)}/>{m("Save this feedback for up to 90 days.")}</label><button type="button" className="secondary" disabled={!consent || !rating || busy} onClick={() => void work(async () => { await api('/feedback', 'POST', { sessionId, rating, text, saveConsent: true, locale }); setText(''); setConsent(false); setStatus(m("Feedback saved.")); })}>{m("Save feedback")}</button></>}
    {mode==='account'&&<><h3>{m("Delete account")}</h3><p>{m("This removes your Firebase sign-in, preferences, saved sessions and feedback. This cannot be undone.")}</p>{!deleting ? <button type="button" className="text-button" onClick={() => setDeleting(true)}>{m("Review account deletion")}</button> : <><label>{m("Confirm with your current password")}<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)}/></label><div className="actions"><button type="button" className="stop" disabled={!password || busy} onClick={() => void work(async () => { const auth = firebaseAuth(), user = auth.currentUser; if (!user?.email) throw new Error(); await reauthenticateWithCredential(user, EmailAuthProvider.credential(user.email, password)); setPassword(''); await api('/me', 'DELETE'); await signOut(auth); onDeleted(); })}>{m("Permanently delete my account")}</button><button type="button" className="secondary" disabled={busy} onClick={() => { setDeleting(false); setPassword(''); }}>{m("Keep account")}</button></div></>}</>}<p role="status">{status}</p></section>;
}
